/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errorsNoConnectionRouteImport } from './routes/(errors)/no-connection'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'

const errors503LazyRouteImport = createFileRoute('/(errors)/503')()
const errors500LazyRouteImport = createFileRoute('/(errors)/500')()
const errors404LazyRouteImport = createFileRoute('/(errors)/404')()
const errors403LazyRouteImport = createFileRoute('/(errors)/403')()
const errors401LazyRouteImport = createFileRoute('/(errors)/401')()
const authSignUpLazyRouteImport = createFileRoute('/(auth)/sign-up')()
const authForgotPasswordLazyRouteImport = createFileRoute(
  '/(auth)/forgot-password',
)()
const AuthenticatedSettingsRouteLazyRouteImport = createFileRoute(
  '/_authenticated/settings',
)()
const AuthenticatedProjectsIndexLazyRouteImport = createFileRoute(
  '/_authenticated/projects/',
)()
const AuthenticatedSettingsAppearanceLazyRouteImport = createFileRoute(
  '/_authenticated/settings/appearance',
)()
const AuthenticatedSettingsAccountLazyRouteImport = createFileRoute(
  '/_authenticated/settings/account',
)()
const AuthenticatedProjectsIdIndexLazyRouteImport = createFileRoute(
  '/_authenticated/projects/$id/',
)()
const AuthenticatedAdminUsersIndexLazyRouteImport = createFileRoute(
  '/_authenticated/admin/users/',
)()
const AuthenticatedAdminTemplatesIndexLazyRouteImport = createFileRoute(
  '/_authenticated/admin/templates/',
)()
const AuthenticatedAdminProjectsIndexLazyRouteImport = createFileRoute(
  '/_authenticated/admin/projects/',
)()
const AuthenticatedAdminAnalyticsIndexLazyRouteImport = createFileRoute(
  '/_authenticated/admin/analytics/',
)()
const AuthenticatedAdminUsersAddLazyRouteImport = createFileRoute(
  '/_authenticated/admin/users/add',
)()
const AuthenticatedAdminUsersIdIndexLazyRouteImport = createFileRoute(
  '/_authenticated/admin/users/$id/',
)()
const AuthenticatedAdminTemplatesIdIndexLazyRouteImport = createFileRoute(
  '/_authenticated/admin/templates/$id/',
)()
const AuthenticatedAdminProjectsIdIndexLazyRouteImport = createFileRoute(
  '/_authenticated/admin/projects/$id/',
)()

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503LazyRoute = errors503LazyRouteImport
  .update({
    id: '/(errors)/503',
    path: '/503',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(errors)/503.lazy').then((d) => d.Route))
const errors500LazyRoute = errors500LazyRouteImport
  .update({
    id: '/(errors)/500',
    path: '/500',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(errors)/500.lazy').then((d) => d.Route))
const errors404LazyRoute = errors404LazyRouteImport
  .update({
    id: '/(errors)/404',
    path: '/404',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(errors)/404.lazy').then((d) => d.Route))
const errors403LazyRoute = errors403LazyRouteImport
  .update({
    id: '/(errors)/403',
    path: '/403',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(errors)/403.lazy').then((d) => d.Route))
const errors401LazyRoute = errors401LazyRouteImport
  .update({
    id: '/(errors)/401',
    path: '/401',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(errors)/401.lazy').then((d) => d.Route))
const authSignUpLazyRoute = authSignUpLazyRouteImport
  .update({
    id: '/(auth)/sign-up',
    path: '/sign-up',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-up.lazy').then((d) => d.Route))
const authForgotPasswordLazyRoute = authForgotPasswordLazyRouteImport
  .update({
    id: '/(auth)/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/forgot-password.lazy').then((d) => d.Route),
  )
const AuthenticatedSettingsRouteLazyRoute =
  AuthenticatedSettingsRouteLazyRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/route.lazy').then((d) => d.Route),
  )
const errorsNoConnectionRoute = errorsNoConnectionRouteImport.update({
  id: '/(errors)/no-connection',
  path: '/no-connection',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsIndexLazyRoute =
  AuthenticatedProjectsIndexLazyRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/projects/index.lazy').then((d) => d.Route),
  )
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsAppearanceLazyRoute =
  AuthenticatedSettingsAppearanceLazyRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/appearance.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedSettingsAccountLazyRoute =
  AuthenticatedSettingsAccountLazyRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/account.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedProjectsIdIndexLazyRoute =
  AuthenticatedProjectsIdIndexLazyRouteImport.update({
    id: '/projects/$id/',
    path: '/projects/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/projects/$id/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedAdminUsersIndexLazyRoute =
  AuthenticatedAdminUsersIndexLazyRouteImport.update({
    id: '/admin/users/',
    path: '/admin/users/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/admin/users/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedAdminTemplatesIndexLazyRoute =
  AuthenticatedAdminTemplatesIndexLazyRouteImport.update({
    id: '/admin/templates/',
    path: '/admin/templates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/admin/templates/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedAdminProjectsIndexLazyRoute =
  AuthenticatedAdminProjectsIndexLazyRouteImport.update({
    id: '/admin/projects/',
    path: '/admin/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/admin/projects/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedAdminAnalyticsIndexLazyRoute =
  AuthenticatedAdminAnalyticsIndexLazyRouteImport.update({
    id: '/admin/analytics/',
    path: '/admin/analytics/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/admin/analytics/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedAdminUsersAddLazyRoute =
  AuthenticatedAdminUsersAddLazyRouteImport.update({
    id: '/admin/users/add',
    path: '/admin/users/add',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/admin/users/add.lazy').then((d) => d.Route),
  )
const AuthenticatedAdminUsersIdIndexLazyRoute =
  AuthenticatedAdminUsersIdIndexLazyRouteImport.update({
    id: '/admin/users/$id/',
    path: '/admin/users/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/admin/users/$id/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedAdminTemplatesIdIndexLazyRoute =
  AuthenticatedAdminTemplatesIdIndexLazyRouteImport.update({
    id: '/admin/templates/$id/',
    path: '/admin/templates/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/admin/templates/$id/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedAdminProjectsIdIndexLazyRoute =
  AuthenticatedAdminProjectsIdIndexLazyRouteImport.update({
    id: '/admin/projects/$id/',
    path: '/admin/projects/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/admin/projects/$id/index.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/no-connection': typeof errorsNoConnectionRoute
  '/settings': typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/500': typeof errors500LazyRoute
  '/503': typeof errors503LazyRoute
  '/': typeof AuthenticatedIndexRoute
  '/settings/account': typeof AuthenticatedSettingsAccountLazyRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceLazyRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexLazyRoute
  '/admin/users/add': typeof AuthenticatedAdminUsersAddLazyRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsIndexLazyRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsIndexLazyRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesIndexLazyRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexLazyRoute
  '/projects/$id': typeof AuthenticatedProjectsIdIndexLazyRoute
  '/admin/projects/$id': typeof AuthenticatedAdminProjectsIdIndexLazyRoute
  '/admin/templates/$id': typeof AuthenticatedAdminTemplatesIdIndexLazyRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdIndexLazyRoute
}
export interface FileRoutesByTo {
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/no-connection': typeof errorsNoConnectionRoute
  '/settings': typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/500': typeof errors500LazyRoute
  '/503': typeof errors503LazyRoute
  '/': typeof AuthenticatedIndexRoute
  '/settings/account': typeof AuthenticatedSettingsAccountLazyRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceLazyRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexLazyRoute
  '/admin/users/add': typeof AuthenticatedAdminUsersAddLazyRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsIndexLazyRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsIndexLazyRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesIndexLazyRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexLazyRoute
  '/projects/$id': typeof AuthenticatedProjectsIdIndexLazyRoute
  '/admin/projects/$id': typeof AuthenticatedAdminProjectsIdIndexLazyRoute
  '/admin/templates/$id': typeof AuthenticatedAdminTemplatesIdIndexLazyRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/no-connection': typeof errorsNoConnectionRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordLazyRoute
  '/(auth)/sign-up': typeof authSignUpLazyRoute
  '/(errors)/401': typeof errors401LazyRoute
  '/(errors)/403': typeof errors403LazyRoute
  '/(errors)/404': typeof errors404LazyRoute
  '/(errors)/500': typeof errors500LazyRoute
  '/(errors)/503': typeof errors503LazyRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountLazyRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceLazyRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexLazyRoute
  '/_authenticated/admin/users/add': typeof AuthenticatedAdminUsersAddLazyRoute
  '/_authenticated/admin/analytics/': typeof AuthenticatedAdminAnalyticsIndexLazyRoute
  '/_authenticated/admin/projects/': typeof AuthenticatedAdminProjectsIndexLazyRoute
  '/_authenticated/admin/templates/': typeof AuthenticatedAdminTemplatesIndexLazyRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexLazyRoute
  '/_authenticated/projects/$id/': typeof AuthenticatedProjectsIdIndexLazyRoute
  '/_authenticated/admin/projects/$id/': typeof AuthenticatedAdminProjectsIdIndexLazyRoute
  '/_authenticated/admin/templates/$id/': typeof AuthenticatedAdminTemplatesIdIndexLazyRoute
  '/_authenticated/admin/users/$id/': typeof AuthenticatedAdminUsersIdIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/otp'
    | '/sign-in'
    | '/no-connection'
    | '/settings'
    | '/forgot-password'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/settings/account'
    | '/settings/appearance'
    | '/admin'
    | '/projects'
    | '/admin/users/add'
    | '/admin/analytics'
    | '/admin/projects'
    | '/admin/templates'
    | '/admin/users'
    | '/projects/$id'
    | '/admin/projects/$id'
    | '/admin/templates/$id'
    | '/admin/users/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/otp'
    | '/sign-in'
    | '/no-connection'
    | '/settings'
    | '/forgot-password'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/settings/account'
    | '/settings/appearance'
    | '/admin'
    | '/projects'
    | '/admin/users/add'
    | '/admin/analytics'
    | '/admin/projects'
    | '/admin/templates'
    | '/admin/users'
    | '/projects/$id'
    | '/admin/projects/$id'
    | '/admin/templates/$id'
    | '/admin/users/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(errors)/no-connection'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/admin/'
    | '/_authenticated/projects/'
    | '/_authenticated/admin/users/add'
    | '/_authenticated/admin/analytics/'
    | '/_authenticated/admin/projects/'
    | '/_authenticated/admin/templates/'
    | '/_authenticated/admin/users/'
    | '/_authenticated/projects/$id/'
    | '/_authenticated/admin/projects/$id/'
    | '/_authenticated/admin/templates/$id/'
    | '/_authenticated/admin/users/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  errorsNoConnectionRoute: typeof errorsNoConnectionRoute
  authForgotPasswordLazyRoute: typeof authForgotPasswordLazyRoute
  authSignUpLazyRoute: typeof authSignUpLazyRoute
  errors401LazyRoute: typeof errors401LazyRoute
  errors403LazyRoute: typeof errors403LazyRoute
  errors404LazyRoute: typeof errors404LazyRoute
  errors500LazyRoute: typeof errors500LazyRoute
  errors503LazyRoute: typeof errors503LazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/no-connection': {
      id: '/(errors)/no-connection'
      path: '/no-connection'
      fullPath: '/no-connection'
      preLoaderRoute: typeof errorsNoConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceLazyRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountLazyRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyRoute
    }
    '/_authenticated/projects/$id/': {
      id: '/_authenticated/projects/$id/'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/templates/': {
      id: '/_authenticated/admin/templates/'
      path: '/admin/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/projects/': {
      id: '/_authenticated/admin/projects/'
      path: '/admin/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AuthenticatedAdminProjectsIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/analytics/': {
      id: '/_authenticated/admin/analytics/'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users/add': {
      id: '/_authenticated/admin/users/add'
      path: '/admin/users/add'
      fullPath: '/admin/users/add'
      preLoaderRoute: typeof AuthenticatedAdminUsersAddLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users/$id/': {
      id: '/_authenticated/admin/users/$id/'
      path: '/admin/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AuthenticatedAdminUsersIdIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/templates/$id/': {
      id: '/_authenticated/admin/templates/$id/'
      path: '/admin/templates/$id'
      fullPath: '/admin/templates/$id'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesIdIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/projects/$id/': {
      id: '/_authenticated/admin/projects/$id/'
      path: '/admin/projects/$id'
      fullPath: '/admin/projects/$id'
      preLoaderRoute: typeof AuthenticatedAdminProjectsIdIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteLazyRouteChildren {
  AuthenticatedSettingsAccountLazyRoute: typeof AuthenticatedSettingsAccountLazyRoute
  AuthenticatedSettingsAppearanceLazyRoute: typeof AuthenticatedSettingsAppearanceLazyRoute
}

const AuthenticatedSettingsRouteLazyRouteChildren: AuthenticatedSettingsRouteLazyRouteChildren =
  {
    AuthenticatedSettingsAccountLazyRoute:
      AuthenticatedSettingsAccountLazyRoute,
    AuthenticatedSettingsAppearanceLazyRoute:
      AuthenticatedSettingsAppearanceLazyRoute,
  }

const AuthenticatedSettingsRouteLazyRouteWithChildren =
  AuthenticatedSettingsRouteLazyRoute._addFileChildren(
    AuthenticatedSettingsRouteLazyRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteLazyRoute: typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedProjectsIndexLazyRoute: typeof AuthenticatedProjectsIndexLazyRoute
  AuthenticatedAdminUsersAddLazyRoute: typeof AuthenticatedAdminUsersAddLazyRoute
  AuthenticatedAdminAnalyticsIndexLazyRoute: typeof AuthenticatedAdminAnalyticsIndexLazyRoute
  AuthenticatedAdminProjectsIndexLazyRoute: typeof AuthenticatedAdminProjectsIndexLazyRoute
  AuthenticatedAdminTemplatesIndexLazyRoute: typeof AuthenticatedAdminTemplatesIndexLazyRoute
  AuthenticatedAdminUsersIndexLazyRoute: typeof AuthenticatedAdminUsersIndexLazyRoute
  AuthenticatedProjectsIdIndexLazyRoute: typeof AuthenticatedProjectsIdIndexLazyRoute
  AuthenticatedAdminProjectsIdIndexLazyRoute: typeof AuthenticatedAdminProjectsIdIndexLazyRoute
  AuthenticatedAdminTemplatesIdIndexLazyRoute: typeof AuthenticatedAdminTemplatesIdIndexLazyRoute
  AuthenticatedAdminUsersIdIndexLazyRoute: typeof AuthenticatedAdminUsersIdIndexLazyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteLazyRoute:
    AuthenticatedSettingsRouteLazyRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedProjectsIndexLazyRoute: AuthenticatedProjectsIndexLazyRoute,
  AuthenticatedAdminUsersAddLazyRoute: AuthenticatedAdminUsersAddLazyRoute,
  AuthenticatedAdminAnalyticsIndexLazyRoute:
    AuthenticatedAdminAnalyticsIndexLazyRoute,
  AuthenticatedAdminProjectsIndexLazyRoute:
    AuthenticatedAdminProjectsIndexLazyRoute,
  AuthenticatedAdminTemplatesIndexLazyRoute:
    AuthenticatedAdminTemplatesIndexLazyRoute,
  AuthenticatedAdminUsersIndexLazyRoute: AuthenticatedAdminUsersIndexLazyRoute,
  AuthenticatedProjectsIdIndexLazyRoute: AuthenticatedProjectsIdIndexLazyRoute,
  AuthenticatedAdminProjectsIdIndexLazyRoute:
    AuthenticatedAdminProjectsIdIndexLazyRoute,
  AuthenticatedAdminTemplatesIdIndexLazyRoute:
    AuthenticatedAdminTemplatesIdIndexLazyRoute,
  AuthenticatedAdminUsersIdIndexLazyRoute:
    AuthenticatedAdminUsersIdIndexLazyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  errorsNoConnectionRoute: errorsNoConnectionRoute,
  authForgotPasswordLazyRoute: authForgotPasswordLazyRoute,
  authSignUpLazyRoute: authSignUpLazyRoute,
  errors401LazyRoute: errors401LazyRoute,
  errors403LazyRoute: errors403LazyRoute,
  errors404LazyRoute: errors404LazyRoute,
  errors500LazyRoute: errors500LazyRoute,
  errors503LazyRoute: errors503LazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
